name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "info: Logging into Docker Hub"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "info: Logged into Docker Hub"

      - name: Build Docker Image
        run: |
          echo "info: Building Docker Image"
          docker build -t gabo8191/docker-graphql:0.0.1 .
          echo "info: Docker Image built"

      - name: Push Docker Image
        run: |
          echo "info: Pushing Docker Image"
          docker push gabo8191/docker-graphql:0.0.1
          echo "info: Docker Image pushed"
